name: Sample apps
on:
  workflow_dispatch:   
  #schedule: 
  #  - cron:  '30 2 * * 1-5'
  # push:
  # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Some name
    container: docker://vespaengine/vespa-build-almalinux-8:latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
          dnf -y install docker-ce protobuf-compiler protobuf-devel python3 python3-pip python3-devel --nobest
          python3 -m pip install --upgrade pip
          python3 -m pip install --ignore-installed -qqq -r test/requirements.txt --user
          python3 -m pip install --upgrade -qqq pytest nbmake onnx onnxruntime torch numpy transformers
          python3 -m pip install --upgrade -qqq pytest nbmake onnx onnxruntime torch numpy transformers --user
          VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")') && \
            curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt && \
            ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/

      - name: Test
        run: |
          ls $GITHUB_WORKSPACE
          #$SD_SOURCE_DIR/test/test.py -v -w $SD_SOURCE_DIR -c $SD_SOURCE_DIR/test/_test_config.yml
          
