name: Verify guides
on:
  workflow_dispatch:   
  #schedule: 
  #  - cron:  '30 2 * * 1-5'
  # push:
  # branches: [ master ]

jobs:
  verify_guides:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - run: echo Hello world!
